### ISSUE TITLE
倒是计时开始了，会一直在后台运行吗

### ISSUE THREAD

**Issue by huizaiyo** [CaMnter/EasyCountDownTextureView#1]
我是listview中每个条目上都有倒计时，这个控件界面onPause()，倒计时的线程还在后台运行么？有没有方法，停止倒计时。

**Comment by CaMnter** [comment]
@huizaiyo  TextureView被回收就停止了，换句话说你Activity finish就回收了。
你可以试试打开demo看看时间，然后手机杀死demo的进程，再去看看时间。

**Comment by huizaiyo** [comment]
我是用在fragmnet中 照这样说 我是在listview中使用了多个倒计时控件，最好在界面不显示的时候将fragment销毁是吧，我发现我小米手机开着几个倒计时，不一会手机就有点发烫

**Comment by CaMnter** [comment]
@huizaiyo app不杀死，会一直跑，你几个倒计时的是app没杀死吧？

**Comment by CaMnter** [comment]
@huizaiyo 我现在在开会，一会写一个手动暂停的方法，然后更一版，稍等一下。

**Comment by huizaiyo** [comment]
好的  你先忙  谢谢啦 @CaMnter

**Comment by huizaiyo** [comment]
能加个倒计时结束的监听吗，我想倒计时结束后，隐藏这个控件，并做一些其他处理

**Comment by CaMnter** [comment]
@huizaiyo 可以，最晚今天晚上。

**Comment by huizaiyo** [comment]
好的 非常感谢  3Q~

**Comment by CaMnter** [comment]
@huizaiyo v1.2 版本了
StyleActivity  有简单介绍。
