### ISSUE TITLE
The hour will reduce 24 when it bigger than 24

### ISSUE THREAD

**Issue by falling** [CaMnter/EasyCountDownTextureView#3]
I want to know why the Hour will reduce 24 when I set it's value bigger than 24.
I hope to count down from 26 hours, but it display only 2 hour, is that a bug? or you just design as it ?

```java
       private int checkCalendarHour(final long millisInFuture, int calendarHour) {
            final int days = (int) (millisInFuture / ONE_DAY);
            if (days > 1) {
                calendarHour += (days - 1) * 24;
            }
            return calendarHour;
        }
```

**Comment by CaMnter** [comment]
很早之前没有这个设计。有一次，用在生产环境上，有这个需求，更了这个功能。

**Comment by CaMnter** [comment]
@falling 这是个 bug。应该是:   
```java
if (days >= 1) {
    calendarHour += days * 24;
}
```   
我之前的也是得显示 26 小时。才加的这个，后来记得改过了，忘记更这里了。

**Comment by falling** [comment]
@CaMnter 我昨天看了一下，还有其他的问题，比如setTimeMinute()这个方法，它修改了分钟数，但是在重新计算总秒数 的时候，没有考虑天数的问题，导致设置以后，小时数被重置为24的余数。

**Comment by CaMnter** [comment]
Calendar 的 hour 就是是不会超过 24 的。超过的，得自己算。

**Comment by CaMnter** [comment]
@falling 真实时间是对的，只是显示小时那错了。其实没那么复杂，只是 Calendar 取时的时候要考虑天数，总时间对就行。

**Comment by CaMnter** [comment]
@falling 是判断错了，漏了 24- 48 之间的判断。
```java
if (days >= 1) {
    calendarHour += days * 24;
}
```
就好了

**Comment by falling** [comment]
比如，我设置了26小时，26分钟，26秒，它开始倒计时了，这时候调用setTimeMinute修改分钟数，这时候小时数会变成2小时，感觉hour的取值可以不用Calendar来拿。
如果第一次修改时间后就不能修改，那倒是没其他的问题。

**Comment by CaMnter** [comment]
原则很简单的，倒计时按秒减总时间。所看到的时间通过 Calendar 展示。但是 Calendar 是日历时间，一天最高只有 24 小时。之前用在业务线上有这个问题，fix 得不够完整。

**Comment by falling** [comment]
嗯。。了解，感觉hour不用Calendar ，要修改的地方就小很多。在第一次运行的时候，存进去的就是完整的小时数就好

**Comment by CaMnter** [comment]
@falling 倒计时 和 显示是独立的。选择 Calendar 只是为了让代码更人性化一点，可读性高，当然也很简单。存在的问题就是 修复一下 Calendar 超过 24 小时的时间就可以。我之前是修复过了，但是 24 - 48 之间漏了。以前在生产环境改过这个问题了，这边这个库忘了改，导致这边没完全 fix 掉。

还是很感谢你能提出这个问题。毕竟这个问题没完全 fix 是很糟糕的吧，233。

**Comment by falling** [comment]
没事，我昨天一个同学用了你的这个库，发现超过24小时的倒计时全都少了一天，哭着找我帮忙。唉…要帮一个只会用不会看源代码的同学，很心累

CaMnter <notifications@github.com>于2017年4月6日周四 上午10:51写道：

**Comment by CaMnter** [comment]
@falling 嗯嗯，我也看了那个项目，Android-TabView-master。对比了一下是哪个版本的代码，就回来改了。
